# Generated by Django 3.1.2 on 2020-10-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_time', models.IntegerField()),
                ('user', models.ManyToManyField(related_name='group', to='app.User')),
            ],
        ),
    ]
