# Generated by Django 3.1.2 on 2020-10-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_group'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='user',
            index_together={('username', 'phone')},
        ),
    ]
